[package]
name = "bio-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
rstest = "0.16.0"
